# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = false

solc = "0.8.17"
src = "src"
test = "test"
libs = ["lib"]
out = "out"

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[rpc_endpoints]
ethereum="https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
localhost="http://localhost:8545"
goerli="https://goerli.infura.io/v3/${ALCHEMY_API_KEY_GOERLI}"